{
    "emmet.triggerExpansionOnTab" : true,
                                    "files.associations" : {"*html" : "html"},

                                                           "editor.linkedEditing" : true,
                                                                                    "emmet.excludeLanguages" : [

                                                                                                                   "markdown"],
                                                                                                               "emmet.includeLanguages" : {
                                                                                                                   "javascript" : "javascriptreact"
                                                                                                               },
                                                                                                                                          "tabnine.experimentalAutoImports" : true,
                                                                                                                                                                              "[javascript]" : {
                                                                                                                                                                                  "editor.defaultFormatter" : "HookyQR.beautify"
                                                                                                                                                                              },
                                                                                                                                                                                               "javascript.updateImportsOnFileMove.enabled" : "always",
                                                                                                                                                                                                                                              "terminal.integrated.tabs.enabled" : true,
                                                                                                                                                                                                                                                                                   "terminal.integrated.allowWorkspaceConfiguration" : true,
                                                                                                                                                                                                                                                                                                                                       "terminal.integrated.defaultProfile.windows" : "Git Bash",
                                                                                                                                                                                                                                                                                                                                                                                      "terminal.integrated.profiles.windows" : {
                                                                                                                                                                                                                                                                                                                                                                                          "C:\\Program Files\\Git\\bin\\bash.exe (migrated)" : {
                                                                                                                                                                                                                                                                                                                                                                                              "path" : "C:\\Program Files\\Git\\bin\\bash.exe",
                                                                                                                                                                                                                                                                                                                                                                                              "args" : []
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                               "editor.formatOnSave" : true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                       "editor.wordWrap" : "off",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "editor.cursorBlinking" : "smooth",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "workbench.iconTheme" : "vscode-icons",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "liveServer.settings.donotVerifyTags" : true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "update.enableWindowsBackgroundUpdates" : false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "update.showReleaseNotes" : false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "update.mode" : "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "[json]" : {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "editor.defaultFormatter" : "esbenp.prettier-vscode"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "bracket-pair-colorizer-2.depreciation-notice" : false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "blockman.n01LineHeight" : 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "workbench.colorCustomizations" : {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //"terminal.foreground": "#65e84a",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //"terminalCursor.foreground": "#edf054",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "editor.lineHighlightBackground" : "#1073cf2d",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "editor.lineHighlightBorder" : "#9fced11f"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "diffEditor.wordWrap" : "off",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "editor.inlayHints.enabled" : false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "editor.minimap.enabled" : false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "git.autofetch" : true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "code-runner.runInTerminal" : true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "editor.guides.indentation" : false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "files.autoSave" : "afterDelay",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "liveSassCompile.settings.formats" : [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "format" : "compressed",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "extensionName" : ".css",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "savePath" : "/dist",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "savePathReplacementPairs" : null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "[html]" : {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "editor.defaultFormatter" : "vscode.html-language-features"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "vsicons.dontShowNewVersionMessage" : true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "explorer.confirmDelete" : false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "code-runner.saveAllFilesBeforeRun" : true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "code-runner.executorMap":
    {

        "javascript" : "node",
                       "java" : "cd $dir && javac $fileName && java $fileNameWithoutExt",
                                "c" : "cd $dir && gcc $fileName -o $fileNameWithoutExt.exe && $dir$fileNameWithoutExt.exe",
                                      "cpp" : "cd $dir && g++ $fileName -o $fileNameWithoutExt.exe && $dir$fileNameWithoutExt.exe",
                                              "zig" : "zig run",
                                                      "objective-c" : "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
                                                                      "php" : "php",
                                                                              "python" : "python -u",
                                                                                         "perl" : "perl",
                                                                                                  "perl6" : "perl6",
                                                                                                            "ruby" : "ruby",
                                                                                                                     "go" : "go run",
                                                                                                                            "lua" : "lua",
                                                                                                                                    "groovy" : "groovy",
                                                                                                                                               "powershell" : "powershell -ExecutionPolicy ByPass -File",
                                                                                                                                                              "bat" : "cmd /c",
                                                                                                                                                                      "shellscript" : "bash",
                                                                                                                                                                                      "fsharp" : "fsi",
                                                                                                                                                                                                 "csharp" : "scriptcs",
                                                                                                                                                                                                            "vbscript" : "cscript //Nologo",
                                                                                                                                                                                                                         "typescript" : "ts-node",
                                                                                                                                                                                                                                        "coffeescript" : "coffee",
                                                                                                                                                                                                                                                         "scala" : "scala",
                                                                                                                                                                                                                                                                   "swift" : "swift",
                                                                                                                                                                                                                                                                             "julia" : "julia",
                                                                                                                                                                                                                                                                                       "crystal" : "crystal",
                                                                                                                                                                                                                                                                                                   "ocaml" : "ocaml",
                                                                                                                                                                                                                                                                                                             "r" : "Rscript",
                                                                                                                                                                                                                                                                                                                   "applescript" : "osascript",
                                                                                                                                                                                                                                                                                                                                   "clojure" : "lein exec",
                                                                                                                                                                                                                                                                                                                                               "haxe" : "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
                                                                                                                                                                                                                                                                                                                                                        "rust" : "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
                                                                                                                                                                                                                                                                                                                                                                 "racket" : "racket",
                                                                                                                                                                                                                                                                                                                                                                            "scheme" : "csi -script",
                                                                                                                                                                                                                                                                                                                                                                                       "ahk" : "autohotkey",
                                                                                                                                                                                                                                                                                                                                                                                               "autoit" : "autoit3",
                                                                                                                                                                                                                                                                                                                                                                                                          "dart" : "dart",
                                                                                                                                                                                                                                                                                                                                                                                                                   "pascal" : "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
                                                                                                                                                                                                                                                                                                                                                                                                                              "d" : "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
                                                                                                                                                                                                                                                                                                                                                                                                                                    "haskell" : "runghc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                "nim" : "nim compile --verbosity:0 --hints:off --run",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "lisp" : "sbcl --script",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "kit" : "kitc --run",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "v" : "v run",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "sass" : "sass --style expanded",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "scss" : "scss --style expanded",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "less" : "cd $dir && lessc $fileName $fileNameWithoutExt.css",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "FortranFreeForm" : "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "fortran-modern" : "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "fortran_fixed-form" : "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "fortran" : "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "sml" : "cd $dir && sml $fileName"
    }
}